csv_to_config.csv_import:
  path: '/admin/config/development/csv_to_config/import/upload'
  defaults:
    _form: '\Drupal\csv_to_config\Form\CSVImportForm'
    _title: 'CSV to Config'
  requirements:
    _permission: 'administer site configuration'
  options:
    _admin_route: TRUE
